-- =========================================================
-- Geographic Analysis
-- =========================================================


/* =========================================================
   1. Which territories/regions generate the highest total sales?
   Purpose:
   Calculate total sales generated by each territory and
   rank territories from highest to lowest.
   ========================================================= */

SELECT
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group],
    SUM(SubTotal) AS Total_Sales
FROM Sales.SalesTerritory t
INNER JOIN Sales.SalesOrderHeader o
    ON t.TerritoryID = o.TerritoryID
GROUP BY
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group]
ORDER BY SUM(SubTotal) DESC;


/* =========================================================
   2. Which territories have the highest number of customers?
   Purpose:
   Count the distinct customers assigned to each territory
   and rank territories from highest to lowest.
   ========================================================= */

SELECT
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group],
    COUNT(DISTINCT c.CustomerID) AS Customer_NO
FROM Sales.SalesTerritory t
INNER JOIN Sales.Customer c
    ON t.TerritoryID = c.TerritoryID
GROUP BY
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group]
ORDER BY COUNT(DISTINCT c.CustomerID) DESC;


/* =========================================================
   3. Which territories have the highest average order value?
   Purpose:
   Calculate the Average Order Value (AOV) for each territory
   and rank territories from highest to lowest.
   ========================================================= */

SELECT
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group],
    AVG(SubTotal) AS AVG_Total_Sales
FROM Sales.SalesTerritory t
INNER JOIN Sales.SalesOrderHeader o
    ON t.TerritoryID = o.TerritoryID
GROUP BY
    t.TerritoryID,
    t.Name,
    t.CountryRegionCode,
    t.[Group]
ORDER BY AVG(SubTotal) DESC;


/* =========================================================
   4. Which territories are growing fastest period-over-period?
   ========================================================= */


/* ---------------------------------------------------------
   PART 1: Check the overall date range of the dataset

   Purpose:
   Identify the first and last available order dates
   to understand the period covered by the data.
   --------------------------------------------------------- */

SELECT
    MIN(OrderDate) AS FIRST_DATE,
    MAX(OrderDate) AS LAST_DATE
FROM Sales.SalesOrderHeader;


/* ---------------------------------------------------------
   PART 2: Check the number of available months per year

   Purpose:
   Determine whether each year represents a full year
   or a partial year before calculating growth.
   --------------------------------------------------------- */

WITH CTE AS
(
    SELECT
        YEAR(OrderDate) AS YEAR_,
        MONTH(OrderDate) AS M_NAME
    FROM Sales.SalesOrderHeader
    GROUP BY
        YEAR(OrderDate),
        MONTH(OrderDate)
)
SELECT
    YEAR_,
    COUNT(M_NAME) AS NO_MONTH_PER_YEAR
FROM CTE
GROUP BY YEAR_;


/* ---------------------------------------------------------
   PART 3: Calculate annual territory growth

   Period:
   2023 vs 2024

   Purpose:
   Compare two complete years using the Growth Rate.

   Note:
   2022 is excluded because it is only a partial year.
   --------------------------------------------------------- */

SELECT
    YEAR_,
    TerritoryID,
    Name,
    CountryRegionCode,
    [Group],
    Total_Sales,
    LAG(Total_Sales) OVER (
        PARTITION BY TerritoryID
        ORDER BY YEAR_
    ) AS PREV_YEAR_SALES,
    Total_Sales - LAG(Total_Sales) OVER (
        PARTITION BY TerritoryID
        ORDER BY YEAR_
    ) AS CHANGE_,
    ROUND(
        (
            Total_Sales
            - LAG(Total_Sales) OVER (
                PARTITION BY TerritoryID
                ORDER BY YEAR_
            )
        ) * 100
        / LAG(Total_Sales) OVER (
            PARTITION BY TerritoryID
            ORDER BY YEAR_
        ),
        2
    ) AS Growth_Rate
FROM
(
    SELECT
        YEAR(o.OrderDate) AS YEAR_,
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group],
        SUM(o.SubTotal) AS Total_Sales,
        t.SalesLastYear
    FROM Sales.SalesTerritory t
    INNER JOIN Sales.SalesOrderHeader o
        ON t.TerritoryID = o.TerritoryID
    WHERE YEAR(o.OrderDate) IN (2023, 2024)
    GROUP BY
        YEAR(o.OrderDate),
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group],
        t.SalesLastYear
) AS YEAR_SALES
ORDER BY
    YEAR_,
    TerritoryID;


/* ---------------------------------------------------------
   PART 4: Calculate H1 territory growth

   Period:
   January-June 2024 vs January-June 2025

   Purpose:
   Compare the same six-month period because the 2025 data
   is only available through June.
   --------------------------------------------------------- */

SELECT
    YEAR_,
    TerritoryID,
    Name,
    CountryRegionCode,
    [Group],
    Total_Sales,
    LAG(Total_Sales) OVER (
        PARTITION BY TerritoryID
        ORDER BY YEAR_
    ) AS PREV_YEAR_SALES,
    Total_Sales - LAG(Total_Sales) OVER (
        PARTITION BY TerritoryID
        ORDER BY YEAR_
    ) AS CHANGE_,
    ROUND(
        (
            Total_Sales
            - LAG(Total_Sales) OVER (
                PARTITION BY TerritoryID
                ORDER BY YEAR_
            )
        ) * 100
        / LAG(Total_Sales) OVER (
            PARTITION BY TerritoryID
            ORDER BY YEAR_
        ),
        2
    ) AS Growth_Rate
FROM
(
    SELECT
        YEAR(o.OrderDate) AS YEAR_,
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group],
        SUM(o.SubTotal) AS Total_Sales
    FROM Sales.SalesTerritory t
    INNER JOIN Sales.SalesOrderHeader o
        ON t.TerritoryID = o.TerritoryID
    WHERE
        YEAR(o.OrderDate) IN (2024, 2025)
        AND MONTH(o.OrderDate) BETWEEN 1 AND 6
    GROUP BY
        YEAR(o.OrderDate),
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group]
) AS YEAR_SALES
ORDER BY
    YEAR_,
    TerritoryID;


/* =========================================================
   5. Which territories are underperforming relative to
      the rest of the business?

   Definition of underperformance:
   - Below-average total sales
   - Above-average customer count
   - Below-average Average Order Value (AOV)

   Purpose:
   Identify territories with a relatively large customer base
   but weaker sales and lower order values than the business
   average.
   ========================================================= */

WITH CTE AS
(
    SELECT
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group],
        ROUND(SUM(o.SubTotal), 2) AS Total_Sales,
        COUNT(DISTINCT c.CustomerID) AS Customer_Count,
        ROUND(AVG(o.SubTotal), 2) AS AOV
    FROM Sales.SalesTerritory t
    INNER JOIN Sales.SalesOrderHeader o
        ON t.TerritoryID = o.TerritoryID
    INNER JOIN Sales.Customer c
        ON o.CustomerID = c.CustomerID
    GROUP BY
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group]
),
CTE2 AS
(
    SELECT
        TerritoryID,
        Name,
        CountryRegionCode,
        [Group],
        Total_Sales,
        Customer_Count,
        AOV,
        CAST(
            AVG(CAST(Total_Sales AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_Total_Sales,
        CAST(
            AVG(CAST(Customer_Count AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_Customer_Count,
        CAST(
            AVG(CAST(AOV AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_AOV
    FROM CTE
)
SELECT
    TerritoryID,
    Name,
    CountryRegionCode,
    [Group],
    Total_Sales,
    Customer_Count,
    AOV,
    AVG_Total_Sales,
    AVG_Customer_Count,
    AVG_AOV
FROM CTE2
WHERE
    Total_Sales < AVG_Total_Sales
    AND AVG_Customer_Count < Customer_Count
    AND AOV < AVG_AOV;


/* =========================================================
   6. Are there territories with fewer customers but
      disproportionately high customer value?

   Definition:
   - Below-average customer count
   - Above-average Average Order Value (AOV)

   Purpose:
   Identify territories where a smaller customer base is
   associated with relatively high-value orders.
   ========================================================= */

WITH CTE AS
(
    SELECT
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group],
        ROUND(SUM(o.SubTotal), 2) AS Total_Sales,
        COUNT(DISTINCT c.CustomerID) AS Customer_Count,
        ROUND(AVG(o.SubTotal), 2) AS AOV
    FROM Sales.SalesTerritory t
    INNER JOIN Sales.SalesOrderHeader o
        ON t.TerritoryID = o.TerritoryID
    INNER JOIN Sales.Customer c
        ON o.CustomerID = c.CustomerID
    GROUP BY
        t.TerritoryID,
        t.Name,
        t.CountryRegionCode,
        t.[Group]
),
CTE2 AS
(
    SELECT
        TerritoryID,
        Name,
        CountryRegionCode,
        [Group],
        Total_Sales,
        Customer_Count,
        AOV,
        CAST(
            AVG(CAST(Total_Sales AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_Total_Sales,
        CAST(
            AVG(CAST(Customer_Count AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_Customer_Count,
        CAST(
            AVG(CAST(AOV AS decimal(18,2))) OVER()
            AS decimal(18,2)
        ) AS AVG_AOV
    FROM CTE
)
SELECT
    TerritoryID,
    Name,
    CountryRegionCode,
    [Group],
    Total_Sales,
    Customer_Count,
    AOV,
    AVG_Total_Sales,
    AVG_Customer_Count,
    AVG_AOV
FROM CTE2
WHERE
    AVG_Customer_Count > Customer_Count
    AND AOV > AVG_AOV;
